### ISSUE TITLE
Cascading reruns of tasks with downstream dependencies

### ISSUE THREAD

**Issue by rsmenon** [mozilla/crontabber#66]
This is more a question than an issue at the moment. Consider the following set of jobs with dependencies parametrized by the date `dt`:

```
A(dt)
|--> B(dt)
|--> C(dt)
     |--> D(dt)
```

Does the package handle (either out of the box or in an experimental/round about way) the case when the job in task A needs to be rerun from some *past date* `d` onwards? This would require not only for A to be rerun for dates >= `d`, but also for all the downstream dependent jobs to be rebuilt due to the changed definition of A. Using the above example:

 - If A is rerun after date `d`, then B, C & D also get rerun for all dates >= `d`
 - If C is rerun, then only D is also rerun.
 - If B or D  need to be rerun after date `d` then nothing else gets rerun.

My understanding from having poked around in the package is that only upstream dependencies are explicitly defined in the task app. The entire DAG could be reconstructed using the postgres tables and the downstream dependencies identified from that. But how would one trigger the jobs (especially those on different machines)? Add some sort of a "DAG monitor" that checks for rerun triggers and then sets a flag on the downstream tasks? 

I don't know the best way forward, but this is a scenario that I've run into quite often (and it only gets worse when the DAG grows), that I've begun to think about writing an extension to the app to handle this. I wanted to get your thoughts on this and perhaps throw some ideas around before I dig myself into a hole :)

**Comment by peterbe** [comment]
First of all, what do you mean by re-run? 
If they're **not backfill based** jobs, and you decide to re-run a job (A or B or C) then the dependency hierarchy does not matter. 

I guess what you're thinking of is that you decide that C needs to be re-run and that crontabber should help you say "If you're going to re-run C, do you also want to re-run D afterwards: [y/N]"

**Comment by rsmenon** [comment]
@peterbe 
> I guess what you're thinking of is that you decide that C needs to be re-run and that crontabber should help you say "If you're going to re-run C, do you also want to re-run D afterwards: [y/N]"

Yup, this is exactly what I mean.

**Comment by peterbe** [comment]
So what you're proposing is basically an extension to the `--job` flag?
http://crontabber.readthedocs.org/en/latest/user/commandlineoptions.html#job-and-force
E.g. `$ crontabber --job=myjob --also-dependents` 
(instead of a CLI style question that pops up)

And that would basically, for you, do the **equivalent** of 
```
$ crontabber --job=A
$ crontabber --job=B
$ crontabber --job=C
$ crontabber --job=D
```

Do you want to write that new feature?

**Comment by peterbe** [comment]
Hmm.. Upon thinking I think I need to help you with your expectations. Your example mentioned with A, B, C, D they all expect a datetime (e.g. `dt`). If you have jobs that are NOT backfill based, you don't get a date input parameter. Jobs that *can* be *re-run* just get a database connection. 

If a job is backfill based, you get a datetime into it always. But with backfill based jobs you can never execute it arbitrarily. I.e. you can't re-run it with a date that has already been given to it.

**Comment by rsmenon** [comment]
@peterbe An extension like what you propose seems reasonable.

I understand that backfill jobs using the `@as_backfill_cron_job` mixin currently don't allow re-runs, but needing to re-run a backfill-able job from some date forward is quite common in analytics ETL pipelines. For example, instead of a [procedure like this](http://crontabber.readthedocs.org/en/latest/user/backfillablejobs.html#an-example-explains-it) that raises an error, we might have something like 

```sql
delete from some_table where dt = run_date;
insert into some_table(dt, total)
select 
    run_date,
    count(distinct some_column)
from some_other_table
where some_condition
group by 1;
```

So even if the job is accidentally run twice on a same date, it doesn't insert multiple rows. 

I wouldn't want to overload the existing decorator but would you be open to adding functionality for a new mixin `@as_backfill_with_rerun` which behaves as I described in the OP?  So if we were to extend the CLI, it would be something like 

```
crontabber --job=A --date=yyyy-mm-dd
```
and the date param gets converted into a `datetime.datetime` object which is then passed to `A.run`. I think what needs to be done is to identify the DAG and extract the downstream dependent jobs from the current job. The actual implementation of this feature could be as simple as resetting the "last run" field in the postgres table for all apps to the supplied date - 1. Then the app just runs as a regular backfill job and runs each one for all dates in between, respecting the upstream dependencies. Does that sound reasonable?

**Comment by peterbe** [comment]
I think the critical thing here is that `--date=yyyy-mm-dd`. And considering that your need comes from real life and not "it would be cool to have" I'm not going to stand in your way. A couple of things to consider...

* We could first start working on the `$ crontabber --job=myjob --also-dependents` functionality. It would be useful to have for non-backfill dates. 
* If you have an infrastructure where jobs are NOT backfill based (and your SQL example seems to indicate so) then you don't need backfilling and you can actually achieve this functionality today. (minus the `--also-dependents` functionality) Let me illustrate:

```python
@using_postgres()
@with_postgres_connection_as_argument()
class MyApp(BaseCronApp):
    required_config = Namespace()
    required_config.add_option('run_date')
    def run(self, connection):
        run_date = self.config.run_date or datetime.date.today()
        ...
```
A bit more work is required to set a smart `from_string_converter` but that would basically be good enough. 

* Lastly, my memory evades me, but I think the hardest part with backfill-based jobs and running them one-off, is that it'd screw up the state and it'd get confused. I guess, if you do have that `@as_backfill_with_rerun` and you run it with `--job=A --date=yyyy-mm-dd` you'd simply just log it but not mess with the state.

**Comment by rsmenon** [comment]
Coming back to this, I've sort of hackily implemented parts of this in my own codebase on top of `BaseCronApp` along the following lines

 - A `MyBaseTask` which subclasses `BaseCronApp` and defines run as 

```python
class MyBaseTask
    def run(self, *args, **kwargs):
        self.execute(*args, **kwargs)

    @classmethod
    def execute(cls, *args, **kwargs):
        raise NotImplementedError
```
and all my tasks then subclass `MyBaseTask` and define the `execute` method. The reason is so that I can run something on-off programmatically without having to instantiate the task object (which then tries to log to the db). As I mentioned earlier, most of my jobs are idempotent (i.e. run them twice and the data in the table will be the same) so it's ok to bypass the logs for past dates.
 - use the topological sort to identify child jobs in the correct order
 - A wrapper function that takes a list of dates and does

```python
tasks = [my_task_1, my_task_2, ...]  # in the correct order in the dag
for date in dates:
    for task in tasks:
        task.execute(date)
```

Works to my satisfaction. It's currently in my codebase and I hadn't written it with upstream contribution in mind, but if you'd like I can flesh out a PR. For now, I'd be fine with closing this issue.
